# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(default='Prescription default text'),
        ),
    ]
